// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMember = `-- name: AddGroupMember :one
INSERT INTO gp_members (gp_members_id, gp_members_user_id, role) 
VALUES ($1, $2, COALESCE(NULLIF($3, '')::role_type, 'member'::role_type))
RETURNING gp_members_id, gp_members_user_id, role
`

type AddGroupMemberParams struct {
	GpMembersID     string      `json:"gp_members_id"`
	GpMembersUserID string      `json:"gp_members_user_id"`
	Column3         interface{} `json:"column_3"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) (GpMember, error) {
	row := q.db.QueryRow(ctx, addGroupMember, arg.GpMembersID, arg.GpMembersUserID, arg.Column3)
	var i GpMember
	err := row.Scan(&i.GpMembersID, &i.GpMembersUserID, &i.Role)
	return i, err
}

const addThreadMember = `-- name: AddThreadMember :one
INSERT INTO thread_members (thread_members_id, thread_members_user_id) 
VALUES ($1, $2)
RETURNING thread_members_id, thread_members_user_id
`

type AddThreadMemberParams struct {
	ThreadMembersID     string `json:"thread_members_id"`
	ThreadMembersUserID string `json:"thread_members_user_id"`
}

func (q *Queries) AddThreadMember(ctx context.Context, arg AddThreadMemberParams) (ThreadMember, error) {
	row := q.db.QueryRow(ctx, addThreadMember, arg.ThreadMembersID, arg.ThreadMembersUserID)
	var i ThreadMember
	err := row.Scan(&i.ThreadMembersID, &i.ThreadMembersUserID)
	return i, err
}

const addUser = `-- name: AddUser :one
/* adduser,
 create group,
  add group members,
   start thread,
    add thread members,
     get dms messages(dm messages for a particular dm chat) ,
      get group messages(messages for a particular group excluding thread messages),
       get thread messages(oder by group and thread name.show all messages for a particular thread,
        the name of the thread and the group to which it belongs),
         get user groups(groups user belongs to), get user threads(threads user is part of),
          get list of groups and users who created the groups,
           get list of threads and users who started the threads,
            get number of thread belonging to a group,
             get list of thread belonging to a group,
              create a message,
               list all groups */ 

INSERT INTO users (fullname, username, email) 
VALUES ($1, $2, $3) RETURNING user_id, fullname, username, email, created_at
`

type AddUserParams struct {
	Fullname string `json:"fullname"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (User, error) {
	row := q.db.QueryRow(ctx, addUser, arg.Fullname, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Fullname,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (gp_name, created_by) 
VALUES ($1, $2) 
RETURNING gp_id, gp_name, created_by, created_at
`

type CreateGroupParams struct {
	GpName    string `json:"gp_name"`
	CreatedBy string `json:"created_by"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.GpName, arg.CreatedBy)
	var i Group
	err := row.Scan(
		&i.GpID,
		&i.GpName,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (sender, content, chat_id, chat_type) 
VALUES ($1, $2, $3, $4) 
RETURNING message_id, sender, content, created_at, chat_id, chat_type
`

type CreateMessageParams struct {
	Sender   *string      `json:"sender"`
	Content  string       `json:"content"`
	ChatID   string       `json:"chat_id"`
	ChatType ChattypeEnum `json:"chat_type"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.Sender,
		arg.Content,
		arg.ChatID,
		arg.ChatType,
	)
	var i Message
	err := row.Scan(
		&i.MessageID,
		&i.Sender,
		&i.Content,
		&i.CreatedAt,
		&i.ChatID,
		&i.ChatType,
	)
	return i, err
}

const getDmMessages = `-- name: GetDmMessages :many
SELECT m.chat_id, m.chat_type, 
(SELECT fullname FROM users 
WHERE user_id = m.sender 
) AS sender_name,

m.content As message, TO_CHAR(m.created_at, 'HH12:MI AM') As time_sent, DATE(m.created_at) AS day_sent
FROM messages m 
WHERE m.chat_type = 'dms' AND m.chat_id = $1 
ORDER BY m.created_at DESC
`

type GetDmMessagesRow struct {
	ChatID     string       `json:"chat_id"`
	ChatType   ChattypeEnum `json:"chat_type"`
	SenderName string       `json:"sender_name"`
	Message    string       `json:"message"`
	TimeSent   string       `json:"time_sent"`
	DaySent    pgtype.Date  `json:"day_sent"`
}

func (q *Queries) GetDmMessages(ctx context.Context, chatID string) ([]GetDmMessagesRow, error) {
	rows, err := q.db.Query(ctx, getDmMessages, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDmMessagesRow{}
	for rows.Next() {
		var i GetDmMessagesRow
		if err := rows.Scan(
			&i.ChatID,
			&i.ChatType,
			&i.SenderName,
			&i.Message,
			&i.TimeSent,
			&i.DaySent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupMessages = `-- name: GetGroupMessages :many
SELECT m.chat_id, m.chat_type, 
(SELECT fullname FROM users 
WHERE user_id = m.sender 
) AS sender_name, 

m.content AS message, TO_CHAR(m.created_at, 'HH12:MI AM') As time_sent, DATE(m.created_at) AS day_sent
FROM messages m
WHERE m.chat_type = 'groups' AND m.chat_id = $1 
ORDER BY m.created_at DESC
`

type GetGroupMessagesRow struct {
	ChatID     string       `json:"chat_id"`
	ChatType   ChattypeEnum `json:"chat_type"`
	SenderName string       `json:"sender_name"`
	Message    string       `json:"message"`
	TimeSent   string       `json:"time_sent"`
	DaySent    pgtype.Date  `json:"day_sent"`
}

func (q *Queries) GetGroupMessages(ctx context.Context, chatID string) ([]GetGroupMessagesRow, error) {
	rows, err := q.db.Query(ctx, getGroupMessages, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupMessagesRow{}
	for rows.Next() {
		var i GetGroupMessagesRow
		if err := rows.Scan(
			&i.ChatID,
			&i.ChatType,
			&i.SenderName,
			&i.Message,
			&i.TimeSent,
			&i.DaySent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupThreads = `-- name: GetGroupThreads :many
SELECT 
(SELECT gp_name FROM groups 
WHERE gp_id = t.gp_id 
) As group_name, 

t.thread_name FROM threads t 
WHERE t.gp_id = $1 
ORDER BY group_name, t.created_at
`

type GetGroupThreadsRow struct {
	GroupName  string `json:"group_name"`
	ThreadName string `json:"thread_name"`
}

func (q *Queries) GetGroupThreads(ctx context.Context, gpID string) ([]GetGroupThreadsRow, error) {
	rows, err := q.db.Query(ctx, getGroupThreads, gpID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupThreadsRow{}
	for rows.Next() {
		var i GetGroupThreadsRow
		if err := rows.Scan(&i.GroupName, &i.ThreadName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupsUserCreated = `-- name: GetGroupsUserCreated :many
SELECT g.gp_name As group_name, 
(SELECT fullname FROM users 
WHERE user_id = g.created_by 
) As creators_name 

FROM groups g 
WHERE g.created_by = $1 
ORDER BY creators_name
`

type GetGroupsUserCreatedRow struct {
	GroupName    string `json:"group_name"`
	CreatorsName string `json:"creators_name"`
}

func (q *Queries) GetGroupsUserCreated(ctx context.Context, createdBy string) ([]GetGroupsUserCreatedRow, error) {
	rows, err := q.db.Query(ctx, getGroupsUserCreated, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupsUserCreatedRow{}
	for rows.Next() {
		var i GetGroupsUserCreatedRow
		if err := rows.Scan(&i.GroupName, &i.CreatorsName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListOfGroups = `-- name: GetListOfGroups :many
SELECT gp_id, gp_name FROM groups 
ORDER BY created_at DESC
`

type GetListOfGroupsRow struct {
	GpID   string `json:"gp_id"`
	GpName string `json:"gp_name"`
}

func (q *Queries) GetListOfGroups(ctx context.Context) ([]GetListOfGroupsRow, error) {
	rows, err := q.db.Query(ctx, getListOfGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetListOfGroupsRow{}
	for rows.Next() {
		var i GetListOfGroupsRow
		if err := rows.Scan(&i.GpID, &i.GpName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT m.message_id, m.chat_type AS message_from,
(SELECT fullname FROM users 
WHERE user_id = m.sender 
) AS sender_name, 

m.content As message, TO_CHAR(created_at, 'HH12:MI AM') As time_sent, DATE(created_at) AS day_sent
FROM messages m 
WHERE m.message_id = $1
`

type GetMessageByIDRow struct {
	MessageID   string       `json:"message_id"`
	MessageFrom ChattypeEnum `json:"message_from"`
	SenderName  string       `json:"sender_name"`
	Message     string       `json:"message"`
	TimeSent    string       `json:"time_sent"`
	DaySent     pgtype.Date  `json:"day_sent"`
}

func (q *Queries) GetMessageByID(ctx context.Context, messageID string) (GetMessageByIDRow, error) {
	row := q.db.QueryRow(ctx, getMessageByID, messageID)
	var i GetMessageByIDRow
	err := row.Scan(
		&i.MessageID,
		&i.MessageFrom,
		&i.SenderName,
		&i.Message,
		&i.TimeSent,
		&i.DaySent,
	)
	return i, err
}

const getThreadMessages = `-- name: GetThreadMessages :many
SELECT m.chat_id, m.chat_type,
(SELECT gp_name FROM groups 
WHERE gp_id = (SELECT gp_id FROM threads 
WHERE thread_id = m.chat_id) 
) AS group_name, 

(SELECT thread_name FROM threads 
WHERE thread_id = m.chat_id 
) AS thread_name, 

(SELECT fullname FROM users 
WHERE user_id = m.sender 
) AS sender_name, 

content As message, TO_CHAR(created_at, 'HH12:MI AM') As time_sent, DATE(created_at) AS day_sent
FROM messages m 
WHERE m.chat_type = 'threads' AND m.chat_id = $1 
ORDER BY m.created_at DESC
`

type GetThreadMessagesRow struct {
	ChatID     string       `json:"chat_id"`
	ChatType   ChattypeEnum `json:"chat_type"`
	GroupName  string       `json:"group_name"`
	ThreadName string       `json:"thread_name"`
	SenderName string       `json:"sender_name"`
	Message    string       `json:"message"`
	TimeSent   string       `json:"time_sent"`
	DaySent    pgtype.Date  `json:"day_sent"`
}

func (q *Queries) GetThreadMessages(ctx context.Context, chatID string) ([]GetThreadMessagesRow, error) {
	rows, err := q.db.Query(ctx, getThreadMessages, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetThreadMessagesRow{}
	for rows.Next() {
		var i GetThreadMessagesRow
		if err := rows.Scan(
			&i.ChatID,
			&i.ChatType,
			&i.GroupName,
			&i.ThreadName,
			&i.SenderName,
			&i.Message,
			&i.TimeSent,
			&i.DaySent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThreadsUserStarted = `-- name: GetThreadsUserStarted :many
SELECT 
(SELECT fullname FROM users 
WHERE user_id = t.created_by 
) As creators_name,

t.thread_name FROM threads t 
WHERE t.created_by = $1 
ORDER BY creators_name
`

type GetThreadsUserStartedRow struct {
	CreatorsName string `json:"creators_name"`
	ThreadName   string `json:"thread_name"`
}

func (q *Queries) GetThreadsUserStarted(ctx context.Context, createdBy *string) ([]GetThreadsUserStartedRow, error) {
	rows, err := q.db.Query(ctx, getThreadsUserStarted, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetThreadsUserStartedRow{}
	for rows.Next() {
		var i GetThreadsUserStartedRow
		if err := rows.Scan(&i.CreatorsName, &i.ThreadName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGroups = `-- name: GetUserGroups :many
SELECT gp_name FROM groups 
WHERE gp_id IN (SELECT gp_members_id FROM gp_members 
                WHERE gp_members_user_id = $1)
`

func (q *Queries) GetUserGroups(ctx context.Context, gpMembersUserID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserGroups, gpMembersUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var gp_name string
		if err := rows.Scan(&gp_name); err != nil {
			return nil, err
		}
		items = append(items, gp_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserThreads = `-- name: GetUserThreads :many
SELECT thread_name FROM threads 
WHERE thread_id IN (SELECT thread_members_id FROM thread_members 
                    WHERE thread_members_user_id = $1)
`

func (q *Queries) GetUserThreads(ctx context.Context, threadMembersUserID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserThreads, threadMembersUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var thread_name string
		if err := rows.Scan(&thread_name); err != nil {
			return nil, err
		}
		items = append(items, thread_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startDm = `-- name: StartDm :one
INSERT INTO dms (user1_id, user2_id) 
VALUES (LEAST($1, $2), GREATEST($1, $2))
RETURNING dm_id, user1_id, user2_id, created_at
`

type StartDmParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) StartDm(ctx context.Context, arg StartDmParams) (Dm, error) {
	row := q.db.QueryRow(ctx, startDm, arg.Column1, arg.Column2)
	var i Dm
	err := row.Scan(
		&i.DmID,
		&i.User1ID,
		&i.User2ID,
		&i.CreatedAt,
	)
	return i, err
}

const startThread = `-- name: StartThread :one
INSERT INTO threads (created_by, gp_id, thread_name, visibility) 
VALUES ($1, $2, $3, COALESCE(NULLIF($4, '')::visibility_enum, 'public'::visibility_enum)) 
RETURNING thread_id, created_by, gp_id, thread_name, visibility, created_at
`

type StartThreadParams struct {
	CreatedBy  *string     `json:"created_by"`
	GpID       string      `json:"gp_id"`
	ThreadName string      `json:"thread_name"`
	Column4    interface{} `json:"column_4"`
}

func (q *Queries) StartThread(ctx context.Context, arg StartThreadParams) (Thread, error) {
	row := q.db.QueryRow(ctx, startThread,
		arg.CreatedBy,
		arg.GpID,
		arg.ThreadName,
		arg.Column4,
	)
	var i Thread
	err := row.Scan(
		&i.ThreadID,
		&i.CreatedBy,
		&i.GpID,
		&i.ThreadName,
		&i.Visibility,
		&i.CreatedAt,
	)
	return i, err
}
