// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ChattypeEnum string

const (
	ChattypeEnumDms     ChattypeEnum = "dms"
	ChattypeEnumGroups  ChattypeEnum = "groups"
	ChattypeEnumThreads ChattypeEnum = "threads"
)

func (e *ChattypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChattypeEnum(s)
	case string:
		*e = ChattypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ChattypeEnum: %T", src)
	}
	return nil
}

type NullChattypeEnum struct {
	ChattypeEnum ChattypeEnum `json:"chattype_enum"`
	Valid        bool         `json:"valid"` // Valid is true if ChattypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChattypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ChattypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChattypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChattypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChattypeEnum), nil
}

type RoleType string

const (
	RoleTypeAdmin  RoleType = "admin"
	RoleTypeMember RoleType = "member"
)

func (e *RoleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleType(s)
	case string:
		*e = RoleType(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleType: %T", src)
	}
	return nil
}

type NullRoleType struct {
	RoleType RoleType `json:"role_type"`
	Valid    bool     `json:"valid"` // Valid is true if RoleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleType) Scan(value interface{}) error {
	if value == nil {
		ns.RoleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleType), nil
}

type VisibilityEnum string

const (
	VisibilityEnumPublic     VisibilityEnum = "public"
	VisibilityEnumRestricted VisibilityEnum = "restricted"
)

func (e *VisibilityEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VisibilityEnum(s)
	case string:
		*e = VisibilityEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for VisibilityEnum: %T", src)
	}
	return nil
}

type NullVisibilityEnum struct {
	VisibilityEnum VisibilityEnum `json:"visibility_enum"`
	Valid          bool           `json:"valid"` // Valid is true if VisibilityEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVisibilityEnum) Scan(value interface{}) error {
	if value == nil {
		ns.VisibilityEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VisibilityEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVisibilityEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VisibilityEnum), nil
}

type Dm struct {
	DmID      string           `json:"dm_id"`
	User1ID   string           `json:"user1_id"`
	User2ID   string           `json:"user2_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type GpMember struct {
	GpMembersID     string       `json:"gp_members_id"`
	GpMembersUserID string       `json:"gp_members_user_id"`
	Role            NullRoleType `json:"role"`
}

type Group struct {
	GpID      string           `json:"gp_id"`
	GpName    string           `json:"gp_name"`
	CreatedBy string           `json:"created_by"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Message struct {
	MessageID string           `json:"message_id"`
	Sender    *string          `json:"sender"`
	Content   string           `json:"content"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	ChatID    string           `json:"chat_id"`
	ChatType  ChattypeEnum     `json:"chat_type"`
}

type Thread struct {
	ThreadID   string             `json:"thread_id"`
	CreatedBy  *string            `json:"created_by"`
	GpID       string             `json:"gp_id"`
	ThreadName string             `json:"thread_name"`
	Visibility NullVisibilityEnum `json:"visibility"`
	CreatedAt  pgtype.Timestamp   `json:"created_at"`
}

type ThreadMember struct {
	ThreadMembersID     string `json:"thread_members_id"`
	ThreadMembersUserID string `json:"thread_members_user_id"`
}

type User struct {
	UserID    string           `json:"user_id"`
	Fullname  string           `json:"fullname"`
	Username  string           `json:"username"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
