// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) (GpMember, error)
	AddThreadMember(ctx context.Context, arg AddThreadMemberParams) (ThreadMember, error)
	AddUser(ctx context.Context, arg AddUserParams) (User, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	GetDmMessages(ctx context.Context, chatID string) ([]GetDmMessagesRow, error)
	GetGroupMessages(ctx context.Context, chatID string) ([]GetGroupMessagesRow, error)
	GetGroupThreads(ctx context.Context, gpID string) ([]GetGroupThreadsRow, error)
	GetGroupsUserCreated(ctx context.Context, createdBy string) ([]GetGroupsUserCreatedRow, error)
	GetListOfGroups(ctx context.Context) ([]GetListOfGroupsRow, error)
	GetMessageByID(ctx context.Context, messageID string) (GetMessageByIDRow, error)
	GetThreadMessages(ctx context.Context, chatID string) ([]GetThreadMessagesRow, error)
	GetThreadsUserStarted(ctx context.Context, createdBy *string) ([]GetThreadsUserStartedRow, error)
	GetUserGroups(ctx context.Context, gpMembersUserID string) ([]string, error)
	GetUserThreads(ctx context.Context, threadMembersUserID string) ([]string, error)
	StartDm(ctx context.Context, arg StartDmParams) (Dm, error)
	StartThread(ctx context.Context, arg StartThreadParams) (Thread, error)
}

var _ Querier = (*Queries)(nil)
