name: code checker

on: [push, pull_request]

jobs:
    golangci:
        name: GolangCI Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-go@v6
              with:
                go-version: stable
            - name: Run golangci-lint
              uses: golangci/golangci-lint-action@v9
              with:
                version: v2.6


    govulncheck_job:
        name: GovulnCheck
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Run govulncheck
              uses: golang/govulncheck-action@v1
              with:
                go-version-input: stable
                go-package: ./...

    test:
        name: test code
        needs: [golangci, govulncheck_job]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-go@v6
              with:
                go-version: stable
            - name: Run Go Tests
              run: go test ./...
              
    build:
        name: build
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-go@v6
              with:
                go-version: stable
            - name: Run Go build
              run: |
                mkdir -p ./bin
                go build -o ./bin/api ./cmd/api
